# Generated by Django 5.0.3 on 2024-08-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0009_places_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
