# Generated by Django 5.0.3 on 2024-06-11 12:13

import django.db.models.deletion
import mapbox_location_field.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Nature', 'Nature-Seeker'), ('Outdoor', 'Outdoor'), ('Instagram', 'Instagrammable'), ('Sporty', 'Sporty'), ('Culture', 'Culture'), ('Shopping', 'Shopping'), ('Beach', 'Beach'), ('Nightlife', 'Nightlife'), ('Animal', 'Animal'), ('Relax', 'Relax'), ('History', 'History')], max_length=200)),
                ('must', models.BooleanField()),
                ('operating', multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FP.places')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FP.states')),
            ],
        ),
    ]
