# Generated by Django 5.0.3 on 2024-07-04 11:47

import FP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='places',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.CreateModel(
            name='PlacesList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('FP.places',),
        ),
        migrations.RemoveField(
            model_name='places',
            name='operating',
        ),
        migrations.AddField(
            model_name='places',
            name='non_operating',
            field=FP.models.MultiSelectField(blank=True, choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='FP.states'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='recm_days',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='places',
            name='tags',
            field=FP.models.MultiSelectField(choices=[('Nature', 'Nature-Seeker'), ('Outdoor', 'Outdoor'), ('Instagram', 'Instagrammable'), ('Sporty', 'Sporty'), ('Culture', 'Culture'), ('Shopping', 'Shopping'), ('Beach', 'Beach'), ('Nightlife', 'Nightlife'), ('Animal', 'Animal'), ('Relax', 'Relax'), ('History', 'History')], max_length=200),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
