# Generated by Django 5.0.3 on 2024-07-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0002_remove_state_places_remove_state_state_delete_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FP.states'),
        ),
    ]
