# Generated by Django 5.0.3 on 2024-07-20 05:45

import FP.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0004_alter_places_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='non_operating',
        ),
        migrations.AddField(
            model_name='places',
            name='operating',
            field=FP.models.MultiSelectField(blank=True, choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('ALL', 'Everyday')], max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='tags',
            field=FP.models.MultiSelectField(choices=[('Nature', 'Nature-Seeker'), ('Outdoor', 'Outdoor'), ('Instagram', 'Instagrammable'), ('Sporty', 'Sporty'), ('Culture', 'Culture'), ('Shopping', 'Shopping'), ('Beach', 'Beach'), ('Nightlife', 'Nightlife'), ('Animal', 'Animal'), ('Relax', 'Relax'), ('History', 'History'), ('Food', 'Food')], max_length=200),
        ),
    ]
