# Generated by Django 5.0.3 on 2024-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0008_alter_places_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
