# Generated by Django 5.0.3 on 2024-07-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0006_places_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='must',
            field=models.BooleanField(null=True),
        ),
    ]
