# Generated by Django 5.0.3 on 2024-07-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0007_alter_places_must'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FP.states'),
        ),
    ]
